### ISSUE TITLE
Auto deploy whenever something merged into main branch

### ISSUE THREAD

**Issue by trihargianto** [sweetcuptea/traxercise#15]
It would be nice whenever something merged into the `main` branch, the app automatically build and deployed so we're able to see the live version.

**Comment by trihargianto** [comment]
@sweetcuptea I'm willing to contribute to this feature if you want  😁

**Comment by sweetcuptea** [comment]
yes please, it would be helpful 😃

**Comment by trihargianto** [comment]
ok, I'll do it once I have free time

**Comment by trihargianto** [comment]
could you please make me as maintainer? @sweetcuptea
